### ISSUE TITLE
Issue when cloning the repository (windows).

### ISSUE THREAD

**Issue by carl-wanninger** [ad-freiburg/ad-blog#37]
When cloning the repository [tested on windows] I receive the following error:

    error: invalid path static/img/project-xsgrep/cache_regex_[Ss][A-Za-z]*[kK].png

And than one only can build the repository by restoring it file by file.
Looks like one of the posts uses "*" for a file name, which might be okay for Linux but not for windows.

**Comment by patrickbr** [comment]
I renamed the file - it wasn't even used in the blog post.
